name: SlimefunAddon

author: CHANGEME

description: A Slimefun4-Addon

main: me.CHANGEME.slimefunaddon.ExampleAddon

website: https://github.com/czszzh/Slimefun_StarTech

version: ${project.version}

api-version: 1.21.1

depend:
- Slimefun
- InfinityExpansion
- Galactifun
- Supreme
- Networks
- TranscEndence

softdepend:
- RykenSlimefunCustomizer