name: SlimefunAddon

author: czssj_ & Add

description: A Slimefun4-Addon

main: me.czssj_.StarTech.StarTech

website: https://github.com/czszzh/Slimefun_StarTech

version: ${project.version}

api-version: 1.21.1

depend:
- Slimefun
- InfinityExpansion
- Galactifun
- Supreme
- Networks
- TranscEndence
- MythicMobs

softdepend:
- RykenSlimefunCustomizer